/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinSessionIdRouteImport } from './routes/join.$sessionId'
import { Route as RoomSessionIdRouteImport } from './routes/room.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSessionIdRoute = JoinSessionIdRouteImport.update({
  id: '/join/$sessionId',
  path: '/join/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSessionIdRoute = RoomSessionIdRouteImport.update({
  id: '/room/$sessionId',
  path: '/room/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join/$sessionId': typeof JoinSessionIdRoute
  '/room/$sessionId': typeof RoomSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join/$sessionId': typeof JoinSessionIdRoute
  '/room/$sessionId': typeof RoomSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join/$sessionId': typeof JoinSessionIdRoute
  '/room/$sessionId': typeof RoomSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/join/$sessionId' | '/room/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/join/$sessionId' | '/room/$sessionId'
  id: '__root__' | '/' | '/join/$sessionId' | '/room/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinSessionIdRoute: typeof JoinSessionIdRoute
  RoomSessionIdRoute: typeof RoomSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$sessionId': {
      id: '/join/$sessionId'
      path: '/join/$sessionId'
      fullPath: '/join/$sessionId'
      preLoaderRoute: typeof JoinSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$sessionId': {
      id: '/room/$sessionId'
      path: '/room/$sessionId'
      fullPath: '/room/$sessionId'
      preLoaderRoute: typeof RoomSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinSessionIdRoute: JoinSessionIdRoute,
  RoomSessionIdRoute: RoomSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
